#ifndef THREE_OMNIWHEEL_CONTROLLER_HPP
#define THREE_OMNIWHEEL_CONTROLLER_HPP

#include <chrono>
#include <cmath>
#include <memory>
#include <queue>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "three_omniwheel_controller/odometry.hpp"
#include "three_omniwheel_controller/speed_limiter.hpp"
#include "three_omniwheel_controller/visibility_control.h"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "hardware_interface/handle.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "odometry.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_box.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "tf2_msgs/msg/tf_message.hpp"

// auto-generated by generate_parameter_library
#include "three_omniwheel_controller/three_omniwheel_controller_parameters.hpp"

namespace three_omniwheel_controller
{
    class ThreeOmniwheelController : public controller_interface::ControllerInterface
    {
        using Twist = geometry_msgs::msg::TwistStamped;
        
    public:
        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        ThreeOmniwheelController();

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration command_interface_configuration() const override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::InterfaceConfiguration state_interface_configuration() const override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::return_type update(
            const rclcpp::Time &time, const rclcpp::Duration &period) override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_init() override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_configure(
            const rclcpp_lifecycle::State &previous_state) override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_activate(
            const rclcpp_lifecycle::State &previous_state) override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_deactivate(
            const rclcpp_lifecycle::State &previous_state) override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_cleanup(
            const rclcpp_lifecycle::State &previous_state) override;

        THREE_OMNIWHEEL_CONTROLLER_PUBLIC
        controller_interface::CallbackReturn on_error(
            const rclcpp_lifecycle::State &previous_state) override;

    protected:
    const char *feedback_type() const;
    const char *imu_feedback_type() const;

        struct DeadWheelHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> feedback;  //can be position or velocity feedback
        };

        controller_interface::CallbackReturn configure_dead_wheel(
            const std::string &which, const std::vector<std::string> &dead_wheel_name,
            std::vector<DeadWheelHandle> &registered_dead_wheel_handles);

        std::vector<DeadWheelHandle> registered_x_wheel_handle_;
        std::vector<DeadWheelHandle> registered_y_wheel_handle_;

        struct IMUHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> orientation;
        };

        controller_interface::CallbackReturn configure_imu(
            const std::string &rcl_send_response, const std::vector<std::string> &sensor_name,
            std::vector<IMUHandle> &registered_sensor_handles);

        std::vector<IMUHandle> registered_imu_handle_;

        struct DriveWheelHandle
        {
            std::reference_wrapper<const hardware_interface::LoanedStateInterface> feedback;  //if needed
            std::reference_wrapper<hardware_interface::LoanedCommandInterface> velocity;
        };

        controller_interface::CallbackReturn configure_drive_wheel(
            const std::string &side, const std::vector<std::string> &drive_wheel_name,
            std::vector<DriveWheelHandle> &registered_drive_wheel_handles);

        std::vector<DriveWheelHandle> registered_front_wheel_handle_;
        std::vector<DriveWheelHandle> registered_back_right_wheel_handle_;
        std::vector<DriveWheelHandle> registered_back_left_wheel_handle_;

        // Parameters from ROS for diff_drive_controller
        std::shared_ptr<ParamListener> param_listener_;
        Params params_;

        Odometry odometry_;

        // Timeout to consider cmd_vel commands old
        std::chrono::milliseconds cmd_vel_timeout_{500};

        std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odometry_publisher_ = nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<nav_msgs::msg::Odometry>>
            realtime_odometry_publisher_ = nullptr;

        std::shared_ptr<rclcpp::Publisher<tf2_msgs::msg::TFMessage>> odometry_transform_publisher_ =
            nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<tf2_msgs::msg::TFMessage>>
            realtime_odometry_transform_publisher_ = nullptr;

        bool subscriber_is_active_ = false;
        rclcpp::Subscription<Twist>::SharedPtr velocity_command_subscriber_ = nullptr;
        rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr
            velocity_command_unstamped_subscriber_ = nullptr;

        realtime_tools::RealtimeBox<std::shared_ptr<Twist>> received_velocity_msg_ptr_{nullptr};

        std::queue<Twist> previous_commands_; // last two commands

        // speed limiters
        SpeedLimiter limiter_linear_x_;
        SpeedLimiter limiter_linear_y_;

        //R2 and L2 joystick
        SpeedLimiter limiter_angular_z_;
        SpeedLimiter limiter_angular_x_;

        bool publish_limited_velocity_ = false;
        std::shared_ptr<rclcpp::Publisher<Twist>> limited_velocity_publisher_ = nullptr;
        std::shared_ptr<realtime_tools::RealtimePublisher<Twist>> realtime_limited_velocity_publisher_ =
            nullptr;

        rclcpp::Time previous_update_timestamp_{0};

        // publish rate limiter
        double publish_rate_ = 50.0;
        rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
        rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};

        bool is_halted = false;
        bool use_stamped_vel_ = true;

        bool reset();
        void halt();
    };
}

#endif