controller_manager:
  ros__parameters:
    update_rate: 10  # coltroller updates every 0.1 secs, how frequest data is processed and commands are sent

    #controllers
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    three_wheel_base_controller:
      type: three_omniwheel_controller/ThreeOmniwheelController

three_wheel_base_controller:
  ros__parameters:
    front_wheel_name: ["front_wheel_joint"]
    back_right_wheel_name: ["back_right_wheel_joint"]
    back_left_wheel_name: ["back_left_wheel_joint"]
    x_dead_wheel_name: ["x_dead_wheel_joint"]
    y_dead_wheel_name: ["y_dead_wheel_joint"]
    chassis_side_length: 0.565
    drive_wheel_radius: 0.5
    dead_wheel_radius: 0.01

    publish_rate: 200.0        #how frequent controller publishes msg(/odmo, /joint_states, etc)
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.1

    use_stamped_vel: false

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    linear.y.has_velocity_limits: true
    linear.y.has_acceleration_limits: true
    linear.y.has_jerk_limits: false
    linear.y.max_velocity: 4.0
    linear.y.min_velocity: -4.0
    linear.y.max_acceleration: 1.0
    linear.y.min_acceleration: -1.0
    linear.y.max_jerk: 0.0
    linear.y.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    angular.x.has_velocity_limits: true
    angular.x.has_acceleration_limits: true
    angular.x.has_jerk_limits: false
    angular.x.max_velocity: 1.0
    angular.x.min_velocity: -1.0
    angular.x.max_acceleration: 1.0
    angular.x.min_acceleration: -1.0
    angular.x.max_jerk: 0.0
    angular.x.min_jerk: 0.0